### ISSUE TITLE
Panel text issue with stringTest=double on iPad2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park-basics#328]
When tested with stringTest=double on iPad2, the text overlaps on itself in the control panel sliders.  See image below.

![img_0037](https://cloud.githubusercontent.com/assets/6396244/8668382/abce1066-29c7-11e5-8462-1636611fd58f.PNG)

**Comment by samreid** [comment]
@jessegreenberg and @jonathanolson has this problem been solved in Scenery? I thought I recalled something about it there.

**Comment by samreid** [comment]
Oh sorry, I thought this was about the blurry double text, but this issue seems to be about the overlapping radio buttons.  I'll set a max width for that panel.

**Comment by jessegreenberg** [comment]
Sorry about the unclear title @samreid, I was referring to the blurry double text.  This issue was not fixed, but it was closed since it does not impact built sims and only seems to happen with Safari and RequireJS.  Here is the scenery issue: https://github.com/phetsims/scenery/issues/469.

**Comment by samreid** [comment]
Thanks @jessegreenberg, makes sense.

**Comment by samreid** [comment]
@ariel-phet and I adjusted the layout in the above commit, closing.
