### ISSUE TITLE
Clear thermal button present when energy is there.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#439]
**Device**
Dell Laptop
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
Found during https://github.com/phetsims/QA/issues/197 (both versions) and may be related to https://github.com/phetsims/energy-skate-park-basics/issues/281
It is possible to see a tiny amount of thermal energy in the bar graph and pie chart, but not be able to click the clear thermal energy button.
**Steps to Reproduce**
1. Go to Friction screen
2. Select the third (wavy) scene
3. Turn on pie chart and bar graph
4. Start the skater on the ramp
5. Periodically dispose of energy.
6. When skater is stopped, dispose of energy one more time.  A bit will be displayed in the charts, but you can't dispose of it.

**Screenshots**
![thermal](https://user-images.githubusercontent.com/41024075/46229104-aa1a7d80-c321-11e8-8943-24c5715d847d.PNG)

**Comment by jessegreenberg** [comment]
Also related to https://github.com/phetsims/energy-skate-park-basics/issues/307. The thermal and total  energy bar have showSmallValuesAsZero false
```js
        if ( showSmallValuesAsZero ) {
          answer = result > 1 ? Math.floor( result ) :
                   result < 1 ? 0 :
                   1;
        }
        else {
          answer = result > 1 ? Math.floor( result ) :
                   result < 1E-6 ? 0 :
                   1;
        }
```

The skater doesn't actually stop, continues to oscillate forever and all of the energy is very small, but this code is keeping thermal and total energies visible.

Maybe we could totally stop the skater in this case? Or we could adjust 1E-6 as the cutoff? Or maybe this is pedagogically useful?

**Comment by jessegreenberg** [comment]
Code comment says
> For thermal and total energy, make sure they are big enough to be visible, see #307. For kinetic and potential, they must go to zero at the endpoints to reach learning goals like "The kinetic energy is zero at the top of the trajectory (turning point)

**Comment by jessegreenberg** [comment]
Here is a comment about why the thresholding is added for thermal and total, but not potential and kinetic https://github.com/phetsims/energy-skate-park-basics/issues/307#issuecomment-62442189

**Comment by jessegreenberg** [comment]
Skater has this Property:
```js
// @public - Enable the "Clear Thermal" buttons but only if the thermal energy exceeds a tiny threshold, so there aren't visual "false positives", see #306
this.allowClearingThermalEnergyProperty
```
And the threshold is 1E-2.

**Comment by jessegreenberg** [comment]
So also related to https://github.com/phetsims/energy-skate-park-basics/issues/306

**Comment by jessegreenberg** [comment]
Ah, so for thermal energy to be visible on the graph the value / 30 needs to be larger than 1E-6. For the button to be enabled, thermal energy needs to be larger than 1E-2. If these match, then the button will be enabled when thermal  energy is visible.

**Comment by jessegreenberg** [comment]
The threshold for enabling the clear thermal energy button now matches the threshold for showing the thermal energy in the bar graph. @KatieWoe can you please make sure this is fixed in master?

**Comment by KatieWoe** [comment]
@jessegreenberg unable to see energy in the bar graph when button in on.  However, I think I'm still seeing something very tiny in the pie chart.
![pie](https://user-images.githubusercontent.com/41024075/47105869-6620e700-d202-11e8-89c1-6ea83f4226eb.PNG)

**Comment by KatieWoe** [comment]
Looks good on master now.

**Comment by jessegreenberg** [comment]
Thanks!
